version: '2'

services:
  openbadge-hub-py:
    build:
      context: .
      dockerfile: ./compose/openbadge-hub-py/Dockerfile_jessie_dev
    volumes:
      - ./src:/app
      - ./data:/data
      - ./logs:/logs
      - ./config:/config
      - /sys/kernel/debug:/sys/kernel/debug
    entrypoint: ./badge_hub.py
    command: -m standalone pull
    env_file: .env
    privileged: true
    network_mode: "host"
